### ISSUE TITLE
No such file or directory - connect(2) for "/tmp/puma-status-1439356636968-18241"

### ISSUE THREAD

**Issue by lalitlogical** [seuros/capistrano-puma#120]
I have successfully deployed my app on EC2 instance. I have Nginx on production server.

I have properly followed the instructions as I got from various sources or blogs on this topic.

I have Gemfile for Capistrano and other gems as below
```
...
gem 'puma'
....

group :development do
  gem 'capistrano', '~> 3.4.0'
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
  gem 'capistrano-ext',     require: false
  gem 'capistrano-faster-assets', '~> 1.0.2'
end
```

I have put below code for puma in deploy.rb

```
set :puma_threads,    [4, 16]
set :puma_workers,    1

set :pty,             true
set :use_sudo,        false
set :puma_bind,       "unix://#{shared_path}/tmp/sockets/puma.sock"
set :puma_conf,       "#{shared_path}/puma.rb"
set :puma_state,      "#{shared_path}/tmp/pids/puma.state"
set :puma_pid,        "#{shared_path}/tmp/pids/puma.pid"
set :puma_access_log, "#{release_path}/log/puma.error.log"
set :puma_error_log,  "#{release_path}/log/puma.access.log"
set :puma_preload_app, true
set :puma_worker_timeout, nil
set :puma_init_active_record, true  # Change to false when not using ActiveRecord

namespace :puma do
  desc 'Create Directories for Puma Pids and Socket'
  task :make_dirs do
    on roles(:app) do
      execute "mkdir #{shared_path}/tmp/sockets -p"
      execute "mkdir #{shared_path}/tmp/pids -p"
    end
  end

  before :start, :make_dirs
end

namespace :deploy do
  desc "Make sure local git is in sync with remote."
  task :check_revision do
    on roles(:app) do
      unless `git rev-parse HEAD` == `git rev-parse origin/capistrano`
        puts "WARNING: HEAD is not the same as origin/capistrano"
        puts "Run `git push` to sync changes."
        exit
      end
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      before 'deploy:restart', 'puma:start'
      invoke 'deploy'
    end
  end

  desc 'Restart application'
  task :restart do
    on roles(:app), in: :sequence, wait: 5 do
      invoke 'puma:restart'
    end
  end

  before :starting,     :check_revision
  after  :finishing,    :compile_assets
  after  :finishing,    :cleanup
  after  :finishing,    :restart
end
```

I have created template for nginx and puma with  ```rails g capistrano:nginx_puma:config``` command.

I have Capfile for puma as below
```
......
require 'capistrano/rails'
require 'capistrano/bundler'
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/faster_assets'

require 'capistrano/rvm'
require 'capistrano/puma'
require 'capistrano/puma/workers'
require 'capistrano/puma/nginx'
......
```

I have run commands in sequence as written below
```
cap production deploy:check
cap production puma:config
cap production puma:nginx_config
cap production deploy:initial
```
After this when I want to run 'cap production deploy' command, I am getting this error.
No such file or directory - connect(2) for "/tmp/puma-status-1439355234544-15824"

Please help!

Thanks

**Comment by lalitlogical** [comment]
When I run 'pumactl restart' command under my rails app directory, it also return same error as
No such file or directory - connect(2) for "/tmp/puma-status-1439357715964-18518"

$ ps aux | grep puma
ubuntu   12791  0.0  3.7 594976 150000 ?       Sl   04:44   0:00 puma 2.12.3 (unix:///var/deploy/myapp/shared/tmp/sockets/puma.sock) [20150812043838]                 
ubuntu   12796  0.0  5.7 1444952 232528 ?      Sl   04:44   0:02 puma: cluster worker 0: 12791 [20150812043838]                                                       
ubuntu   18528  0.0  0.0  10432   672 pts/1    S+   05:36   0:00 grep --color=auto puma

**Comment by uzzer** [comment]
same problem for me, there must something wrong with how to restart puma

**Comment by lhagemann** [comment]
I too am seeing the same error.

```
capistrano (3.4.0)
capistrano-bundler (1.1.4)
capistrano-rails (1.1.3, 1.1.2)
capistrano-rbenv (2.0.3)
capistrano3-puma (0.9.0)
```

**Comment by lhagemann** [comment]
I observed this issue arise after updating from puma 2.11.x to 2.13.x .... and discovered this is in the puma changeling:

```
 === 2.12.0 / 2015-07-14

* Make pumactl load config/puma.rb by default

```

**Comment by ghargrove** [comment]
I don't know if this helps anyone but I ran into this issue today (Oct 19) and after checking out the code in the master branch it looks like it's been updated to use the -F flag for tasks such as halt, etc. 

I temporarily changed my Gemfile to pull from the master branch instead of '~> 1.2.1' and the tasks seem to run ok.

**Comment by mpospelov** [comment]
@ghargrove Thanks, solved with updating to latest version

**Comment by wiserfirst** [comment]
I'm using the latest code on master branch, but still get similar error when running `cap staging deploy`:
```
INFO [f5e54127] Running RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 ~/.rbenv/bin/rbenv exec bundle exec pumactl -S /var/www/rails-apps/rails-api/shared/tmp/pids/puma.state restart on demo-api.fastrackexpress.com.au
DEBUG [f5e54127] Command: cd /var/www/rails-apps/rails-api/current && ( export RBENV_ROOT="~/.rbenv" RBENV_VERSION="2.2.3" RACK_ENV="staging" ; RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 ~/.rbenv/bin/rbenv exec bundle exec pumactl -S /var/www/rails-apps/rails-api/shared/tmp/pids/puma.state restart )
DEBUG [f5e54127]        No such file or directory - connect(2) for /tmp/puma-status-1449795429764-31328
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host demo-api.fastrackexpress.com.au: Exception while executing on host demo-api.fastrackexpress.com.au: bundle exit status: 1
bundle stdout: No such file or directory - connect(2) for /tmp/puma-status-1449795429764-31328
bundle stderr: Nothing written

SSHKit::Runner::ExecuteError: Exception while executing on host demo-api.fastrackexpress.com.au: bundle exit status: 1
bundle stdout: No such file or directory - connect(2) for /tmp/puma-status-1449795429764-31328
bundle stderr: Nothing written

SSHKit::Command::Failed: bundle exit status: 1
bundle stdout: No such file or directory - connect(2) for /tmp/puma-status-1449795429764-31328
bundle stderr: Nothing written

Tasks: TOP => deploy:restart
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing on host demo-api.fastrackexpress.com.au: Exception while executing on host demo-api.fastrackexpress.com.au: bundle exit status: 1
bundle stdout: No such file or directory - connect(2) for /tmp/puma-status-1449795429764-31328
bundle stderr: Nothing written
```
Can somebody please help. Thanks!

**Comment by lhagemann** [comment]
@wiserfirst the output from your run suggests it is not using the updated command, 

`DEBUG [f5e54127] Command: cd /var/www/rails-apps/rails-api/current && ( export RBENV_ROOT="~/.rbenv" RBENV_VERSION="2.2.3" RACK_ENV="staging" ; RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 ~/.rbenv/bin/rbenv exec bundle exec pumactl -S /var/www/rails-apps/rails-api/shared/tmp/pids/puma.state restart )`

does not include the `-F` flag.


What does your Gemfile look like ... you must pull directly from the git repo master to get the new code, there is no updated Gemfile for `capistrano3-puma` that includes the patch to fix this issue.

**Comment by wiserfirst** [comment]
@lhagemann Thank you for pointing out that I'm not using the updated command. 

My Gemfile for `capistrano3-puma`:
```
  gem 'capistrano3-puma', :git => 'git@github.com:seuros/capistrano-puma.git', :ref => 'c1d705d',  require: false
```
I think this should be fine. The reason I'm still using the old command is when I ran `cap staging deploy` (without `bundle exec`), the bundled version of `capistrano3-puma` was not used. But when I try to run `bundle exec cap staging deploy`, I get a different error:
```
INFO [d4c9406f] Running bundle exec pumactl -S /var/www/rails-apps/rails-api/shared/tmp/pids/puma.state -F /var/www/rails-apps/rails-api/shared/puma.rb restart on demo-api.fastrackexpress.com.au
DEBUG [d4c9406f] Command: cd /var/www/rails-apps/rails-api/current && ( export RBENV_ROOT="~/.rbenv" RBENV_VERSION="2.2.3" RACK_ENV="staging" ; bundle exec pumactl -S /var/www/rails-apps/rails-api/shared/tmp/pids/puma.state -F /var/www/rails-apps/rails-api/shared/puma.rb restart )
DEBUG [d4c9406f]        bash: bundle: command not found
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host demo-api.fastrackexpress.com.au: pumactl exit status: 127
pumactl stdout: bash: bundle: command not found
pumactl stderr: Nothing written

SSHKit::Command::Failed: pumactl exit status: 127
pumactl stdout: bash: bundle: command not found
pumactl stderr: Nothing written

Tasks: TOP => puma:restart
(See full trace by running task with --trace)
```
Essentially when running the `pumactl` command, the `RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 ~/.rbenv/bin/rbenv exec` was not included, which makes this command fail.

So I'm now a bit confused about how am I supposed to run `cap` tasks. Thanks!

**Comment by imnanshu** [comment]
@ghargrove, thanks for your help. I sovled the issue with 'master' branch.

**Comment by lalitlogical** [comment]
I have also resolved the issue with updating Gemfile as below in development group.

`gem 'capistrano3-puma', github: "seuros/capistrano-puma"`

Thanks for all of you
